version: '2'
services:
  web:
    build: .
    command: yarn start-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_URL: "mongo"
      MONGO_DB_NAME: "comments"
      PORT: "8000"
      NODE_ENV: "development"
  mongo:
    image: mongo