apiVersion: v1
kind: Service
metadata: 
  name: mongo
  labels:
    app: mern-example
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mern-example
    tier: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  labels:
    app: mern-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mern-example
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mern-example
        tier: backend
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo
          mountPath: /var/lib/mongo:rw
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo-claim