apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas:  {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
    spec:
     containers:
      - name: {{  .Chart.Name  }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.containerPort }} 
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: MONGO_URL
            value: {{ .Values.services.mongo.url }}
          - name: MONGO_DB_NAME
            value: "comments"
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3000"
